import { Montserrat } from 'next/font/google'
import './globals.css'
import Footer from "../containers/Footer/footer"
import Navbar from '@/components/Navbar'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable:'--font-mont'
 })

export const metadata = {
  title: 'Freelance - Clément FELICES',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {

  return (
    <html lang="fr">
      <script src="https://kit.fontawesome.com/061f1c17d4.js" crossorigin="anonymous" async></script>
      <body className={`${montserrat.variable} font-mont bg-light w-full min-h-screen`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
